name: Trigger-ttcli

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger:
    uses: ./.github/workflows/choco.yml
    with:
      choco-package-name: ttcli
      choco-source: https://push.chocolatey.org/
    secrets:
      choco-api-key: ${{ secrets.CHOCOLATEY_API_KEY }}
